name: 构建

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "docker/**"
      - "**.sh"
      - "**.json"

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: dva3221
            version: 7.0.1-42218
          - platform: dva3221
            version: 7.1.0-42661

    steps:
      - name: 检出项目文件
        uses: actions/checkout@v2

      # - name: 缓存加速
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       cache/*.pat
      #       docker/downloads/*.txz
      #     key: ${{matrix.platform}}-${{matrix.version}}-${{ hashFiles('global_config.json') }}

      - name: 准备构建环境
        run: |
          ./redpill_tool_chain.sh build ${{matrix.platform}}-${{matrix.version}}

      - name: 配置引导镜像
        run: |
          cp sample_user_config.json ${{matrix.platform}}_user_config.json

          # 调整SN和MAC 最好使用 actions secrets 引入
          sed -i -e 's\1234XXX123\${{ secrets.DS918_SN }}\g' -e 's\XXYYXXYYXXYY\${{ secrets.DS918_MAC }}\g' ${{matrix.platform}}_user_config.json

          # 调整直通 PCI 的 SATA 顺序
          sed -i -e 's/${{ secrets.DS918_MAC }}"/&,\n\t"DiskIdxMap": "0600"/' ${{matrix.platform}}_user_config.json

          cat ${{matrix.platform}}_user_config.json

      - name: 添加扩展驱动
        if: matrix.platform != 'dva3221'
        run: |
          ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-boot-wait.json
          ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-acpid.json
          ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-virtio.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000/releases/dva3221_42218.json

      - name: 添加扩展驱动[dva3221]
        if: matrix.platform == 'dva3221'
        run: |
          echo '等待整理兼容性扩展~😀'
          ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-boot-wait.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000/releases/dva3221_42218.json

      - name: 添加 Misc shell
        run: |
          ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-misc.json

      - name: 添加 jumkey.dtb !!!Create your own device tree binary!!!
        if: matrix.platform == 'ds920p' || matrix.platform == 'ds1621p' || matrix.platform == 'ds2422p'
        run: |
          ./redpill_tool_chain.sh add https://github.com/tossp/redpill-tool-chain/raw/master/extensions/redpill-dtb.json
          echo '!!!Create your own device tree binary!!!'
          echo 'see https://github.com/jumkey/redpill-load/blob/develop/redpill-dtb/README.md'

      - name: 编译引导镜像
        run: |
          ./redpill_tool_chain.sh auto ${{matrix.platform}}-${{matrix.version}}

      - name: 上传引导镜像到 github actions
        uses: actions/upload-artifact@v2
        with:
          name: dsm-${{matrix.platform}}-${{matrix.version}}
          path: images/redpill-*.img
          if-no-files-found: error

      - name: 删除旧的工作流
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 6
